XORG_PREFIX=/usr/local
PATH="$PATH:$XORG_PREFIX/bin"

LP="$PREFIX/include"
CPPFLAGS="$CPPFLAGS -I$LP"
CPATH="$CPATH:$LP"
C_INCLUDE_PATH="$C_INCLUDE_PATH:$LP"
CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:$LP"
OBJC_INCLUDE_PATH="$OBJC_INCLUDE_PATH:$LP"
unset LP

LP="$PREFIX/lib"
LDFLAGS="$LDFLAGS -L$LP"
LIBRARY_PATH="$LIBRARY_PATH:$LP"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LP"
LD_RUN_PATH="$LD_RUN_PATH:$LP"
unset LP

LP="$PREFIX/lib/pkgconfig"
PKG_CONFIG_LIBDIR="$PKG_CONFIG_LIBDIR:$LP"
PKG_CONFIG_PATH="$XORG_PREFIX/share/pkgconfig:$LP:$PKG_CONFIG_PATH"
unset LP

XORG_CONFIG="--prefix=$XORG_PREFIX --disable-shared --enable-static"
ACLOCAL="aclocal -I $XORG_PREFIX/share/aclocal"

export XORG_PREFIX PATH
export CPPFLAGS CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH
export LDFLAGS LIBRARY_PATH LD_LIBRARY_PATH LD_RUN_PATH
export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH
export XORG_CONFIG ACLOCAL

